
version: 1
formatters:
  default: 
    format: "%(asctime)s : %(name)s.%(funcName)s : %(levelname)s : %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
loggers:
  defaullogger:
    level: DEBUG
    handlers: [console]
    propogate: no
root:
  level: DEBUG
  handlers: [console]